apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: chemcom-api
spec:
  environments:
    - name: prod
    - name: dev
      build:
        from: main
  components:
    - name: api
      src: ./src
      ports:
        - name: http
          port: 5000
      publicPort: http
      secrets:
        - azure__ClientSecret
        - azure__ClientId
        - ClientSecret
        - KeyVaultEndpoint
      environmentConfig:
        - environment: dev
          identity: 
            azure:
              clientId: ca6bee5a-c263-460e-83cd-294987f16755
          runAsNonRoot: true
          variables:
            ASPNETCORE_URLS: "http://*:5000"
            AllowCorsDomains: "https://frontend-chemcom-dev.radix.equinor.com,http://localhost:3000"
          replicas: 2
          monitoring: true
          resources:
            requests:
              memory: "368Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
        - environment: prod
          identity: 
            azure:
              clientId: 31931248-fa75-4501-9de2-4d53cc28da35
          runAsNonRoot: true
          variables:
            ASPNETCORE_URLS: "http://*:5000"
            AllowCorsDomains: "http://localhost:3000,https://chemcom.equinor.com,https://frontend-chemcom-prod.radix.equinor.com"
          replicas: 2
          monitoring: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
