name: API
on:
  repository_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./src/Chemcom.sln

      - name: Build
        run: dotnet build ./src/Chemcom.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Start Docker container
        run: |
          docker run -d --name test-container mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
          docker ps -a

      - name: Test
        run: dotnet test ./src/IntegrationTests

      - name: Get Docker container logs
        run: docker logs test-container

      - name: Cleanup Docker containers
        run: docker rm -f $(docker ps -a -q)
