name: API
on:
  repository_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./src/Chemcom.sln

      - name: Build
        run: dotnet build ./src/Chemcom.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
        ports:
          - 1433:1433
        options: >-
          --env SA_PASSWORD=MyMssqlPassword@12345
          --env ACCEPT_EULA=Y
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"        
     
      - name: Print MSSQL logs
        run: |
          CONTAINER_ID=$(docker ps -q --filter ancestor=mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04)
          docker logs $CONTAINER_ID

      - name: Test
        run: dotnet test ./src/IntegrationTests
