name: API
on:
  repository_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./src/Chemcom.sln

      - name: Build
        run: dotnet build ./src/Chemcom.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
        ports:
          - 1433:1433
        options: >-
          --env SA_PASSWORD=MyMssqlPassword@12345
          --env ACCEPT_EULA=Y
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          
      - name: Wait for MSSQL to be ready
        run: |
          echo "Waiting for MSSQL to start..."
          for i in {1..60}; do
            if nc -z localhost 1433; then
              echo "MSSQL is up and running"
              break
            fi
            echo "Waiting for MSSQL to start... ($i/60)"
            sleep 5
          done
          if ! nc -z localhost 1433; then
            echo "MSSQL failed to start"
            exit 1
          fi

      - name: Print MSSQL logs
        run: docker logs $(docker ps -q --filter ancestor=mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04)

      - name: Test
        run: dotnet test ./src/IntegrationTests
